# Exercise indexing and slicing

## Table of Contents
* [Introduction](#Introduction) 
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules) 
* [Exercises](#Exercises)
    * [Exercise 1D Array](#Exercise-1D-Array)
    * [Exercise 2D Array](#Exercise-2D-Array)
    * [Exercise 3D Array](#Exercise-3D-Array)
    * [Exercise 4D Array](#Exercise-4D-Array)
* [Licenses](#Licenses) 

## Introduction



This notebook provides a small collection of exercises about indexing and slicing for numpy arrays. You will start working with 1D arrays working your way up to 4D. It will be always possible to choose between different styles of solving an exercise but try to use "get all (:)" or slicing if a task offers it to be more efficient and shorten your code.

## Requirements 
### Knowledge

This notebook is the exercise part for the chapters about indexing and slicing from the notebook NumpyAndArrays, so all the knowledge you will need to solve these exercises is provided by this theory notebook.

## Modules

In [4]:
import numpy as np

# Exercises

## Exercise 1D Array

In [2]:
A1 = np.arange(10)
print(A1)

[0 1 2 3 4 5 6 7 8 9]


**Task:** Print the first and the last element.

In [5]:
print(A1[-1])
print(A1[0])

9
0


In [3]:
print(A1)

[0 1 2 3 4 5 6 7 8 9]


**Task:** Print each element with even index.

In [6]:
for i in range(len(A1)):
    if i % 2 == 0:
        print(A1[i])

0
2
4
6
8


**Task:** Print the first four elements.

In [7]:
for i in range(4):
    print(A1[i])

0
1
2
3


**Task** Print the last three elements.

In [12]:

for i in range(4):
    i = i * (-1)
    if i != 0:
        print(A1[i])

9
8
7


**Task** Print element four to eight.

In [14]:
print(A1[4:9])

[4 5 6 7 8]


## Exercise 2D Array 

In [15]:
np.random.seed(42)
M1 = 100*np.random.rand(9,7).round(2)
print(M1)

[[37. 95. 73. 60. 16. 16.  6.]
 [87. 60. 71.  2. 97. 83. 21.]
 [18. 18. 30. 52. 43. 29. 61.]
 [14. 29. 37. 46. 79. 20. 51.]
 [59.  5. 61. 17.  7. 95. 97.]
 [81. 30. 10. 68. 44. 12. 50.]
 [ 3. 91. 26. 66. 31. 52. 55.]
 [18. 97. 78. 94. 89. 60. 92.]
 [ 9. 20.  5. 33. 39. 27. 83.]]


**Task** Print the first and the last row with one slice operation.


In [23]:
#print every 7th elem between start and end
print(M1[1::7])

[[87. 60. 71.  2. 97. 83. 21.]
 [ 9. 20.  5. 33. 39. 27. 83.]]


**Task** Print all elements less than 10.

In [33]:
print(M1)
for i in M1:
    for j in range(len(i)):
        if i[j] < 10:
            print (i[j])


[[37. 95. 73. 60. 16. 16.  6.]
 [87. 60. 71.  2. 97. 83. 21.]
 [18. 18. 30. 52. 43. 29. 61.]
 [14. 29. 37. 46. 79. 20. 51.]
 [59.  5. 61. 17.  7. 95. 97.]
 [81. 30. 10. 68. 44. 12. 50.]
 [ 3. 91. 26. 66. 31. 52. 55.]
 [18. 97. 78. 94. 89. 60. 92.]
 [ 9. 20.  5. 33. 39. 27. 83.]]
6.0
2.0
5.0
7.000000000000001
3.0
9.0
5.0


**Task** Print each even row.

In [39]:
print(M1)
print("-------")
print(M1[0::2])

[[37. 95. 73. 60. 16. 16.  6.]
 [87. 60. 71.  2. 97. 83. 21.]
 [18. 18. 30. 52. 43. 29. 61.]
 [14. 29. 37. 46. 79. 20. 51.]
 [59.  5. 61. 17.  7. 95. 97.]
 [81. 30. 10. 68. 44. 12. 50.]
 [ 3. 91. 26. 66. 31. 52. 55.]
 [18. 97. 78. 94. 89. 60. 92.]
 [ 9. 20.  5. 33. 39. 27. 83.]]
-------
[[37. 95. 73. 60. 16. 16.  6.]
 [18. 18. 30. 52. 43. 29. 61.]
 [59.  5. 61. 17.  7. 95. 97.]
 [ 3. 91. 26. 66. 31. 52. 55.]
 [ 9. 20.  5. 33. 39. 27. 83.]]


**Task** Print each odd column.

In [46]:
#print every second elem from every row
print(M1[0:,1::2])

[[95. 60. 16.]
 [60.  2. 83.]
 [18. 52. 29.]
 [29. 46. 20.]
 [ 5. 17. 95.]
 [30. 68. 12.]
 [91. 66. 52.]
 [97. 94. 60.]
 [20. 33. 27.]]


__Task__ Print the elements of the even rows and the odd columns.

**Task** Print all elements from the following matrix with a pair of even indices ([0,2],[2, 2], [4,2],.. etc.).

In [ ]:
M1 = 100*np.random.rand(5,7).round(2)
print(M1)

## Exercise 3D Array

In [ ]:
np.random.seed(42)
M = np.random.randint(10, size=(2,2,10))
print(M)
# here we have four (most) internal array

**Task** Print the first and the last internal vector-array, i.e.

    [[6 3 7 4 6 9 2 6 7 4]
     [8 2 4 2 6 4 8 6 1 3]]

**Task** Print the last element from each internal array.

    [4 1 3 3]

**Task** Print every second element from the second internal array.
    
    [3 7 5 1 5]

**Task** Print every element with odd index from each internal array.

    [[[3 4 9 6 4]
      [7 2 4 7 1]]

     [[0 5 0 2 3]
      [2 2 4 6 3]]]

In [ ]:
np.random.seed(42)
M = 100*np.random.rand(10,2,9).round(2)
print(M)

## Exercise 4D Array

In [ ]:
np.random.seed(42)
M = np.random.randint(0,100, size=(2,2,3,3))
print(M)

**Task** Print the central element from each internal matrix, i.e.

    [60  2 59 58]

**Task:** Get the second column from each matrix, i.e.

    [[[92 60 86]
      [87  2  1]]

     [[37 59 75]
      [88 58 59]]]

**Task:** Get the second row from each matrix, i.e.

    [[[71 60 20]
      [23  2 21]]

     [[63 59 20]
      [90 58 41]]]

**Task:** Get every element with an even index pair from each matrix.

    [[[[51 14]
       [82 74]]

      [[74 99]
       [52 87]]]
     ....

**Task:** Get the diagonal from each matrix.



Consider now the following 4D array.

In [ ]:
np.random.seed(42)
M = 100*np.random.rand(6,2,6,4).round(2)
print(M)

**Task** Print from the second matrix of the inner matrix pair each second row.


    [[[46. 79. 20. 51.]
      [ 7. 95. 97. 81.]
      [12. 50.  3. 91.]]

     [[ 1. 82. 71. 73.]
      [86. 62. 33.  6.]
      [89. 47. 12. 71.]]
    ....

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

exercise_indexing_and_slicing       
Oliver Fischer <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2019 Oliver Fischer  

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

